### ISSUE TITLE
I want to ask if I can use the SDXL model? And is it possible to output a larger size? Currently, it is at 512px output.

### ISSUE THREAD

**Issue by D-Mad** [BlueDyee/TF-GPH#2]

**Comment by BlueDyee** [comment]
Yes, definitely.
But, there is two thing you need to notice
1. Memory requirement: the tfgph for original SD model already require 24GB VRAM. SDXL should require more.
2. Architectural difference: SDXL have more attention layer, so you might need to modify the attention control part.

**Comment by D-Mad** [comment]
Thank you. Do you intend to publish the training code for the model?
